spring:
  application:
    name: listflix
  datasource:
    url: jdbc:postgresql://localhost:5432/listflix
    username: postgres
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

  file:
    name: app.log